from ..generators import *
from .general import header, footer
from .definition.definition import definitions

properties = TableFields([
    "Strong limit",
    "Weak limit",
    "Regular",
    "Wordly",
    "Small",
    "Weakly inaccessible",
    "Strong inaccessible",
    "Alpha inaccessible",
    "Hyper inaccessible",
    "Weakly mahlo",
    "Strongly mahlo",
    "Alpha mahlo",
    "Hyper mahlo",
    "Reflecting",
    "Weakly compact",
    "Pimn indescridable",
    "Totally indescridable",
    "Lambda unfoldable",
    "Unfoldable",
    "Nu indescridable",
    "Lambda shrewd",
    "Shrewd",
    "Ethereal",
    "Subtle",
    "Almost ineffable",
    "Ineffable",
    "N ineffable",
    "Totally ineffable",
    "Remarkable",
    "Alpha erdos",
    "0dash",
    "Gamma iterable",
    "Gamma erdos",
    "Almost ramsey",
    "Jonsson",
    "Rowbottom",
    "Ramsey",
    "Ineffably ramsey",
    "Completely ramsey",
    "Strongly ramsey",
    "Super ramsey ",
    "Measurable",
    "0cross",
    "Lambda strong",
    "Strong",
    "Tall",
    "Woodin",
    "Weakly hyper woodin",
    "Shelah",
    "Hyper woodin",
    "Superstrong",
    "Subcompact",
    "Strongly compact",
    "Supercompact",
    "Hypercompact",
    "Eta extendible",
    "Extendible",
    "Vopenka",
    "Shelah for supercompactness",
    "High jump",
    "N superstrong",
    "N almost huge",
    "N super almost huge",
    "N huge",
    "N superhuge",
])

cardinal = [header, definitions, properties, footer]
