from general import header, footer

definition_knot = TableFields(["Definition",
                               "Conway",
                               "Dowker"])

properties = TableFields(["Alexander polynomial",
                          "Algebraic concordanc order",
                          "A-polynomial",
                          "Arc index",
                          "Arf invariant",
                          "Braid index",
                          "Braid length",
                          "Bridge index",
                          "Chern-simons invariant",
                          "Complement",
                          "Component count",
                          "Conway polynomial",
                          "Crosscap number",
                          "Crossing number",
                          "Determinant",
                          "Four-ball crossing number",
                          "Full symmetry group",
                          "Genus",
                          "Group",
                          "Homfly polynomial",
                          "Homflypt polynomial",
                          "Jones polynomial",
                          "Kauffman polynomial",
                          "Khovanov polynomial",
                          "Khovanov torsion polynomial",
                          "Linking matrix",
                          "Linking number",
                          "Longitude length",
                          "Longitude translation",
                          "Maximum cusp volume",
                          "Meridian length",
                          "Meridian translation",
                          "Morse-novikov number",
                          "Nakanishi index",
                          "Nullity",
                          "Other short geodesics",
                          "Ozsvath-szabo tau-invariant",
                          "Polygon index",
                          "Positive braid",
                          "Positive braid notation",
                          "Positive",
                          "Positive pd notation",
                          "Quasipositive braid notation",
                          "Quasipositive",
                          "Rasmussen invariant",
                          "Ropelength",
                          "Seifert matrix",
                          "Show polynomials as coefficient vectors",
                          "Signature function",
                          "Signature",
                          "Small or large",
                          "Smooth 4d crosscap number",
                          "Smooth concordance genus",
                          "Smooth concordance order",
                          "Smooth concordance crosscap number",
                          "Smooth four genus",
                          "Splitting number",
                          "Stick number",
                          "Strongly quasipositive braid notation",
                          "Strongly quasipositive",
                          "Super bridge index",
                          "Symmetry type",
                          "Three genus",
                          "Thurston-bennequin number",
                          "Topological 4d crosscap number",
                          "Topological concordance genus",
                          "Topological concordance order",
                          "Topological concordance crosscap number",
                          "Topological four genus",
                          "Torsion numbers",
                          "Total curvature",
                          "Tricolorable",
                          "Tunnel number",
                          "Turaev genus",
                          "Unknotting number",
                          "Unlinking number",
                          "Volume",
                          "Width",
                          "Gauss",
                          "A-b notation",
                          "Rational",
                          "Tangle",
])

knot = [header, definition_knot, properties, footer]
