from ...generators import *
from ..general.namesNotationsDenotedBy import *
from ..general.typ import typDic
from .name import algebra_name_formatted
from ..util import *
from ..style import *

v1 = bareFieldOrDefault("value (mathjax)", "a")
v2 = bareFieldOrDefault("value2 (mathjax)", "b")
base = bareFieldOrDefault("base element (mathjax)", "r")


inner_function = TableFields(
    [
        {"field": "Ring-base",
         "label": "Base",
         "classes": "Definition6"},
        {"field": "Field-base",
         "label": "Base",
         "classes": "Definition6"},
        {"field": "+",
         "classes": "Definition",
         "label": ["\\(",
                   v1,
                   " + ",
                   v2,
                   "=\\) "],
         },
        {"field":    "0",
         "classes": "Definition2"},
        {"field":    "-",
         "classes": "Definition3",
         "label": ["\\(-",
                   v1,
                   "=\\) "],
         },
        {"field":    "*",
         "classes": "Definition4",
         "label": ["\\(",
                   v1,
                   " * ",
                   v2,
                   "=\\) "],
         },
        {"field":    "1",
         "classes": "Definition5"},
        {"field":    "÷",
         "classes": "Definition6",
         "label": ["\\(1 / ",
                   v1,
                   "=\\) "],
         },
        {"field":    "\\",
         "classes": "Definition",
         "label": ["\\(",
                   v1,
                   " \\ ",
                   v2,
                   "=\\) "],
         },
        {"field":    "×",
         "classes": "Definition7",
         "label": ["\\(",
                   base,
                   " \\times ",
                   v1,
                   "=\\) "],
         },
        {"field":    "⋀",
         "classes": "Definition8",
         "label": ["\\(",
                   v1,
                   " \\wedge ",
                   v2,
                   "=\\) "],
         },
        {"field":    "⋁",
         "classes": "Definition9",
         "label": ["\\(",
                   v1,
                   " \\vee ",
                   v2,
                   "=\\) "],
            },
        {"field":    "→",
         "classes": "Definition",
         "label": ["\\(",
                   v1,
                   " \\to ",
                   v2,
                   "=\\) "],
         },
        {"field":    "¬",
         "classes": "Definition4",
         "label": ["\\(¬",
                   v1,
                   "=\\) "],
         },
        {"field":    "◁",
         "classes": "Definition5",
         "label": ["\\(",
                   v1,
                   " \\triangleleft ",
                   v2,
                   "=\\) "],},
    ],
    emphasizing=decorateQuestion,
    name="Inner functions",
    suffix=hr
)

presentation = ("Relation",
                PotentiallyNumberedFields(label=Cascade("Relations",
                                                        QuestionnedField(
                                                            "Generating family"),
                                                        {"Generating family"}),
                                          greater=5,
                                          numbered_field=numbered_field,
                                          fieldPrefix="Relation",
                                          suffix=hr))
outer_function = TableFields(
    ["Graduation",
     {"field":"Norm",
      "label": ["\\(\left|", v1, "\\right|=\\)",]},
     "Euclidean function",
     "Quadratic form",
     ],
    name="Outer functions"
)
definition = Cascade("Definitions",
                     [DecoratedField("Set", suffix=hr),
                      presentation,
                      inner_function,
                      outer_function],
                     {"Inner functions", "Outer functions", "Relations", "Set"})

properties = TableFields(
    ["Principal ideal",
     "Integral",
     "Unique factorization",
     "Closed",
     "Commutative",
     "Not associative",
     "Right-distributive",
     "Complete",
     "Idempotent",
     "Base",
     "Dimension",
     typDic,
     "Free family",
     "Generating family",
     "Inner product",
     "Cover",
     "Faithful",
     "Minimals",
     "Maximals",
     "Well-founded",
     "Units",
     "Zero divisors",
     ],
    name="Properties"
)

algebra = addBoilerplate([
    namesNotationsDenotedBy,
    algebra_name_formatted,
    definition,
    properties,
])
